pipeline {
   agent any

   environment {
           DOCKER_REG = "registry.cn-chengdu.aliyuncs.com/lura"
           DOCKER_REPOSITORY = "${DOCKER_REG}/lura-gateway-server"
           DOCKER_IMAGE = "${DOCKER_REPOSITORY}:build-${BUILD_NUMBER}"
       }
   stages {

         stage("build & dockerize") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'aliyun', passwordVariable: 'password', usernameVariable: 'username')]) {
                        sh 'echo ${password} |sudo docker login --username=${username}  registry.cn-chengdu.aliyuncs.com --password-stdin'
                        sh 'sudo docker build -t ${DOCKER_IMAGE} -f lura-gateway-server/Dockerfile .'
                        sh 'sudo docker push ${DOCKER_IMAGE}'
                        sh 'sudo docker rmi ${DOCKER_IMAGE}'
                }

            }
        }


        stage('Deploy to k8s') {
            steps {
                dir('lura-gateway-server') {
                    sh '''echo 'Deploy....' '''
                    sh 'envsubst < deployment.yml | sudo kubectl apply -f -'
                }
           }
        }
   }
}
